import { auth } from "@/auth";
import "./globals.css";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider session={await auth()}>
      <html lang="en">
        <body className={inter.className}>
          <Toaster position="top-right" />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
